### PR TITLE
[GBR-36]: fixed failing tests

### PR DESCRIPTION
**Pull request by mikeborozdin**
Hi,

This pull requests fixes the failing test, I described in https://github.com/caitp/grunt-bower-release/issues/36

### CODE REVIEW

**Comment by caitp** [comment]
ah, a recent change I made broke this, and I didn't notice because travis was green.

I need to re-organize the travis scripts to make sure to exit with a non-zero status when there are test failures. Want to add that change to the CL? If not I can take care of that separately

**Comment by mikeborozdin** [comment]
Hi @caitp,

Thanks! The CL? The changelog? I think we might need to bump the version number up to 0.0.6.

**Comment by caitp** [comment]
changelist, the pull request basically

**Comment by mikeborozdin** [comment]
Caitlin,

Sorry, I'm a bit confused, do you want me to modify .travis.yml? I'm not that familiar with its configuration yet...

**Comment by caitp** [comment]
okay, don't worry about it, I'll fix that separately

**Pull request closed without merging**
